services:
  # Nginx Service
  personal-notifier-nginx:
    image: nginx:latest      # Use official Nginx image
    container_name: personal-notifier-nginx
    ports:
      - "8080:80"           # Map port 8080 on our PC to 80 in container
    volumes:
      - "$PWD/app:/var/www/app:rw"  # Mount same source code
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - personal-notifier-php                 # Wait for PHP container
    networks:
      - personal-notifier-network
    restart: unless-stopped

    # PHP Service
  personal-notifier-php:
    build:
      context: .              # Build context is current directory
      dockerfile: ./.docker/php/Dockerfile
    container_name: personal-notifier-php # Name our container
    volumes:
      - "$PWD/app:/var/www/app:rw"   # Mount our source code
    networks:
      - personal-notifier-network          # Connect to our network
    environment:
      PHP_IDE_CONFIG: serverName=personal-notifier # For Xdebug
    # Make container restart unless stopped manually
    restart: unless-stopped

networks:
  personal-notifier-network:
    driver: bridge          # Standard Docker network type
