doctrine:
  dbal:
    default_connection: default
    connections:
      default:
        url: '%env(resolve:DATABASE_URL)%'
        charset: utf8
    types:
      uuid_type: App\Infrastructure\Persistence\Doctrine\Type\IdType
      reminder_type_type: App\Infrastructure\Persistence\Doctrine\Type\ReminderTypeType
      repeat_interval_type: App\Infrastructure\Persistence\Doctrine\Type\RepeatIntervalType
  orm:
    default_entity_manager: default
    auto_generate_proxy_classes: true
    enable_lazy_ghost_objects: true
    controller_resolver:
      auto_mapping: false
    entity_managers:
      default:
        connection: default
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        report_fields_where_declared: true
        mappings:
          Domain:
            is_bundle: false
            type: attribute
            dir: '%kernel.project_dir%/src/Domain'
            prefix: 'App\Domain'

when@test:
  doctrine:
    dbal:
      # "TEST_TOKEN" is typically set by ParaTest
      dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
  doctrine:
    dbal:
      connections:
        default:
          schema_filter:
    orm:
      auto_generate_proxy_classes: false
      proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
      query_cache_driver:
        type: pool
        pool: doctrine.system_cache_pool
      result_cache_driver:
        type: pool
        pool: doctrine.result_cache_pool

  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
          adapter: cache.app
        doctrine.system_cache_pool:
          adapter: cache.system
